# Generated by Django 5.2.8 on 2025-12-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_rename_latitude_pokemonentity_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='lot',
            new_name='lon',
        ),
    ]
